### PR TITLE
Add security group labels, bump alpine version

### PR DESCRIPTION
**Pull request by emmanuel**
This is a bit of a mixed bag. The main addition here is to capture a node's security groups from the metadata service along with the other labels.

### CODE REVIEW

**Comment by emmanuel** [comment]
Also, I have a commit in my repo to replace alpine, owing to the 'broken' DNS resolution behavior of musl. That DNS behavior prevented me from using `https://kubernetes` as the value for `CONTROLLER_ENDPOINT`. I used my org's baseimage (`nordstrom/baseimage-ubuntu:14.04.3`) as an alternative, but I'm not sure what an acceptable generic alternative might be, in order to submit that change as a pull request.

**Comment by eliaslevy** [comment]
:+1:  looks good.

Regarding Alpine, I am going to keep this image on Alpine for the time being.  I realize having to use fully qualified domain names is pain, but its fine for the time being.  From the musl mailing list I gather that one of the k8s devs have convinced the musl developer to add support for the `search` feature in `resolv.conf`.  That hasn't yet hit the musl Git repo, but I hope that it does soon and that Alpine then updates so we can all get relative domain names working again.

**Comment by eliaslevy** [comment]
BTW, my latest commits replaced the use of `CONTROLLER_ENDPOINT`.  Now it just uses the `KUBERNETES_SERVICE_HOST` env variable that k8s makes available automatically.  See 41fe132e0d78d57291e18c1e52cc4ad638237b43.

**Comment by eliaslevy** [comment]
@emmanuel see the latest commits.  The security groups label has been converted into an annotation.

**Pull request merged**
